### ISSUE TITLE
Automatic Table of Contents for large readmes

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#151]
I haven't really thought this one through yet, but it seems to be a popular request: https://github.com/isaacs/github/issues/215

**Comment by DrewML** [comment]
This would be great. How would you feel about a floating TOC? Might not have to be the whole menu displayed, but just some way that you can quickly hop to other sections when you're not at the top.

**Comment by sindresorhus** [comment]
Really depends on how well it's implemented. Could be annoying quick if done wrong. Maybe mock-up an example?

**Comment by hkdobrev** [comment]
If this is available in Refined GitHub I'd prefer to have it behind a button. Perhaps similar to the edit button we place in the readme.

**Comment by DrewML** [comment]
Button makes sense - if we didn't have one, then we'd probably need to implement heuristics to try and guess when a readme has it's own TOC, so we could hide our implementation.

**Comment by sindresorhus** [comment]
What kind of button? Where?

Honestly, I'm not even sure this makes sense. Just thought I'd bring it up.

**Comment by hkdobrev** [comment]
> What kind of button? Where?

I thought we could add a TOC button next to the edit button for the readme in the top right corner which would toggle the TOC. So you'll click it only when needed and can click it again to hide the TOC if it's overlaying something.

> Honestly, I'm not even sure this makes sense.

Me too. I'd need a TOC only for very big readmes which I rarely encounter and some of these big readmes already have a TOC inline or they render the readme with a TOC externally on a documentation website or a documentation service like Read the docs. I'm fine with both including or not including this in the extension.

**Comment by Mottie** [comment]
I have a [userscript that adds a TOC](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-table-of-contents) to both readme and wiki pages, you guys are welcome to check it out.

**Comment by willklein** [comment]
I implemented this as its own extension last year: [GitHub Markdown Menu](https://github.com/willklein/github-markdown-menu). I wanted to start rolling out more GH hacks and found this project (yay!).

I could port this to Refined GitHub if others find it useful. Let me know what you think of the implementation. The screenshots are self-explanatory though. If you install the extension, the button icon broke because I was piggy backing on their icon font, but they moved to SVG. I was going to fix it, but maybe I deprecate and add a working version to Refined GH.

**Comment by willklein** [comment]
May I add: this was invaluable for me and my coworkers. We had some extensive READMEs for internal projects, and I've found other places like the Awesome lists where quick ToC navigation is useful. As others guessed, putting it behind a button was a great solution. That kept it unobtrusive, and works well when there is already a ToC in the Markdown. This also works with any Markdown file, not just READMEs.

**Comment by hkdobrev** [comment]
@willklein this is looking great, thanks for sharing!

@sindresorhus @DrewML Do you think we can just link to that extension in the readme?

**Comment by willklein** [comment]
I fixed the missing icon issue in willklein/github-markdown-menu#9. @laughedelic pointed out that this doesn't work with Refined GitHub on repo homepages at the moment. That's because my extension tries to insert content into the header which Refined GitHub has removed. I'm working on a fix in willklein/github-markdown-menu#11.

I'm still happy either way to keep this separate or merge it to Refined GitHub.

**Comment by willklein** [comment]
Well, unless someone knows a secret trick to delay one extension from firing until after another has finished, my extension won't be able to know when to hook in to the DOM and inject its content. I tried `setTimeout`, but that results in `Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src assets-cdn.github.com".`.

I think it would be best to port the markdown menu into Refined GitHub. If others agree, I'll be happy to put together a PR.

**Comment by DrewML** [comment]
@hkdobrev That's fine with me - no need to be a monolith if @willklein's extension already handles it well.

@willklein That looks great! I'm sure we could find a way to play nicely - I think the question is whether or not we have any work to do in this extension to help make the two play nicer. I'll leave this open while the compatibility issues are still present, and will hop over to https://github.com/willklein/github-markdown-menu/issues/11 to try and help out.

**Comment by DrewML** [comment]
Going to close for now, since there are > 1 other extensions in the wild that do exactly this. Happy to re-open if someone thinks of a good reason this would make more sense in `refined-github`.
