### ISSUE TITLE
Add a link to `useful-forks`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3682]
The forks list page should have a button/link to a service that lists useful forks for the current project.

Feature location: https://github.com/sindresorhus/refined-github/network/members
Button URL: https://useful-forks.github.io?repository=sindresorhus/refined-github

This is a super easy feature, it just needs to create a link and position it somewhere on that page.

The button URL hasn't been implemented by https://github.com/useful-forks yet.

---

_Simplified request from https://github.com/sindresorhus/refined-github/issues/3638_

**Comment by payne911** [comment]
> The button URL hasn't been implemented by https://github.com/useful-forks yet.

Done! :)

Try it out: https://useful-forks.github.io?repository=EsotericSoftware/kryonet

> Feature location: https://github.com/sindresorhus/refined-github/network/members

You're making me wonder: maybe it could be a button positioned next to the Fork button all the time, instead of only within the Fork's page itself. Somewhere around there:

![image](https://user-images.githubusercontent.com/38117856/96954396-51e2e500-14c1-11eb-9c66-9bd3ee1e16bf.png)

**Comment by fregante** [comment]
As I said previously, this is not something most people need most of the time, so it won't be added to _every page on every repository._ The forks list is where I'd expect this feature to be found, and maybe also: https://github.com/sindresorhus/refined-github/network

I'm imagining it in the top-right corner of each page (still not in the header) but exploration welcome

**Comment by payne911** [comment]
Okay, I might have some time to work on this. However, looking at the `refined-github` code-base is a bit daunting.

Can you point me toward a feature which would resemble what I'll be trying to achieve?

**Comment by fregante** [comment]
Something like this: https://github.com/sindresorhus/refined-github/blob/main/source/features/download-folder-button.tsx

Some context: The `if` is irrelevant in this case. GitHub change layout at some point so we still support the old one in some cases.

**Comment by payne911** [comment]
For the `include: [ ... ]`, I can't seem to find a constant which points to the `Insights -> Forks` or `Insights -> Network` pages.

Am I the first one implementing a feature for those? If so, where/how should I add that constant?

**Comment by fregante** [comment]
You can add it inline for now. Before the PR is merged you can move it to https://github.com/fregante/github-url-detection

Refer to that module to see what those function look like.

**Comment by payne911** [comment]
> You can add it inline for now.

You mean, like this?

```
void features.add(__filebasename, {
	init
});
```

I tried adding a `console.log` in the `init` function to see if that meant the feature would be activated everywhere, but it didn't seem to do much.

(Sorry for needing so much guidance.)

**Comment by fregante** [comment]
Make sure you’re also including that file in `refined-github.ts` and use `import` instead of require

**Comment by payne911** [comment]
> use `import` instead of `require`

I tried that initially, but it would give me an error:

![image](https://user-images.githubusercontent.com/38117856/107248080-f56bed00-69ff-11eb-83a9-8db763783fec.png)

**Comment by payne911** [comment]
Any thoughts on this preliminary sneak-peek ?

![image](https://user-images.githubusercontent.com/38117856/107256825-fe60bc80-6a07-11eb-93d5-7c3e8e20e922.png)

![image](https://user-images.githubusercontent.com/38117856/107256806-f4d75480-6a07-11eb-90f8-4ab321713d62.png)
