### ISSUE TITLE
Home page feed not loading

### ISSUE THREAD

**Issue by j1nxie** [sindresorhus/refined-github#3712]
It looks like the main GitHub page is broken after installing Refined GitHub and just shows up as blank after briefly showing "Loading activity..."
URL: https://github.com/
Screenshot: https://i.imgur.com/v2Ib29X.png

I've tried uninstalling Refined GitHub and the main feed loads fine, 100% this is a problem from the extension's part.

**Comment by fregante** [comment]
> I've tried uninstalling Refined GitHub and the main feed loads fine, 100% this is a problem from the extension's part.

It could also be a conflict with other extensions. I use Chrome and the newsfeed loads. 

Try disabling others extensions as well to find what conflicts. It might be a content blocker

**Comment by j1nxie** [comment]
Hmm, I've tried disabling uBlock Origin to test but it looks like the All activity feed doesn't load for me. Recent activity works though, for unknown reasons.

**Comment by yakov116** [comment]
Do you see any console errors?

**Comment by j1nxie** [comment]
https://i.imgur.com/BCYyRS5.png

yeah i just screenshotted one quickly and this seems to be it.

**Comment by fregante** [comment]
I fixed one of those errors in https://github.com/sindresorhus/refined-github/commit/3caa8c8bdc4635bc53f61cc0e38182add2c828f3

I don't know if this will fix your problem, but the new version will be published in 12 hours, so tomorrow update and try again.

Regarding the other 2: I think they started lazy-loading the header user dropdown, so those 2 features need to be updated.

**Comment by dgadelha** [comment]
Same issue on Firefox, disabling `hide-useless-newsfeed-events` brings the home page feed back (maybe the whole idea of this is that the entire newsfeed is useless? xD).

**Comment by fregante** [comment]
`hide-useless-newsfeed-events` is CSS-only, so if that fixes the problem it means that they are probably doing AB testing with new classes. 

*Only they who are chosen can restore peace. ⚔️ *

i.e. PR welcome

**Comment by yakov116** [comment]
> AB testing

Defiantly I am running on 2 computers and one is not working correctly (sometimes) and one is.

**Comment by MohamedElashri** [comment]
Why this issue get closed?
The problem still occurs, I tried `hide-useless-newsfeed-events` but it is not working on **Edge browser**

**Comment by NN---** [comment]
Still happens with Firefox 90.

**Comment by fregante** [comment]
This is not a bug. `hide-noisy-newsfeed-events` hides many events. If your newsfeed contains 100% noise then it will be empty.
