### ISSUE TITLE
Additional whitespace when viewing pull requests when there is no white spacing between characters

### ISSUE THREAD

**Issue by AeroEchelon** [sindresorhus/refined-github#612]
Weird spacing introduced while viewing:

| With Github Refined  	| Without Github Refined    |
|---------	|-----------|
| ![image](https://user-images.githubusercontent.com/2360095/28089300-8f7ec270-6656-11e7-9909-983b21d555d7.png)  |		   ![image](https://user-images.githubusercontent.com/2360095/28089318-a157d874-6656-11e7-9082-be5ec03e18ba.png)     |

**Comment by ramlmn** [comment]
This issue is already being addressed by #608.

/cc @bfred-it @sindresorhus Can you look into this ASAP?

**Comment by bfred-it** [comment]
@AeroEchelon can you give us a link?

**Comment by bfred-it** [comment]
@AeroEchelon this might be fixed by #613, have a look.

**Comment by AeroEchelon** [comment]
Thanks @bfred-it for following up but it is still occurring on a repository that I'm working on. I uninstalled Refined Github and reinstalled it from the store and I'm still having the same problems. It seems to only happen on pull requests in my repos and nothing else.

Here's another example of it:

![image](https://user-images.githubusercontent.com/2360095/28173082-6279e64a-67bb-11e7-812a-eb6251a530ae.png)

You can see when I highlight the text that there is no whitespace character just some character spacing artifact.

I tried looking for this exact same behaviour on some public repos but couldn't find any example of it.

**Comment by bfred-it** [comment]
Can you get show me the dom? Is it GitHub or GitHub Enterprise?

**Comment by AeroEchelon** [comment]
Regular Github! But it seems like I've found some similar behaviour here. See in "With" the white spacing when highlighting the text at beginning of line compared to "Without". Unsure if this is the intentional behaviour:

| With  	| Without    |
|---------	|-----------|
|![image](https://user-images.githubusercontent.com/2360095/28180597-90b9a690-67d3-11e7-9ea8-e21cb5ca2c86.png)   |	![image](https://user-images.githubusercontent.com/2360095/28180573-83c013ac-67d3-11e7-8a23-177154ebca40.png)	        |

**Source**
https://github.com/sindresorhus/refined-github/pull/619/commits/d04481d6a336d0f1032cc8d2ce89344951f79468#diff-95ffcbff3c841ad0a802793cabd8940eR107

**Comment by bfred-it** [comment]
I'm not seeing it in either unified nor split view with #613 applied:

<img width="530" alt="screen shot 2017-07-14 at 13 27 02" src="https://user-images.githubusercontent.com/1402241/28199435-2f556b94-6898-11e7-9359-89f38f5a646a.png">

Make sure you test it without other extensions and that #613 is actually built and loaded.

Also it'd be great to see the HTML of one of those `<tr>`s, like so:

<details>

```html
<tr class="refined-github-diff-signs">
    <td class="blob-num blob-num-addition empty-cell selected-line"></td>

    <td id="diff-95ffcbff3c841ad0a802793cabd8940eR107" data-line-number="107" class="blob-num blob-num-addition js-linkable-line-number selected-line"></td>

  <td class="blob-code blob-code-addition selected-line">
      <button class="btn-link add-line-comment js-add-line-comment js-add-single-line-comment" data-path="src/content.js" data-anchor="diff-95ffcbff3c841ad0a802793cabd8940e" data-position="4" data-line="107" type="button" aria-label="Add line comment"><svg aria-hidden="true" class="octicon octicon-plus" height="16" version="1.1" viewBox="0 0 12 16" width="12"><path fill-rule="evenodd" d="M12 9H7v5H5V9H0V7h5V2h2v5h5z"></path></svg></button>

    <span class="blob-code-inner">	} <span class="pl-k">else</span> {</span>

  </td>
</tr>
```
</details>

**Comment by AeroEchelon** [comment]
I'm not too familiar with web debugging. If you could provide the exact steps I should take to provide you with the information that you need, I am willing to assist.   

I am still seeing this issue against the following Github Refined version. I opened by Chrome browser in Incognito, enabled **only** the Github Refined extension in incognito mode and saw that it was still showing the extra spacing.

![image](https://user-images.githubusercontent.com/2360095/28225186-c11f75ea-689f-11e7-8923-c6864051128d.png)

**Comment by sindresorhus** [comment]
@AeroEchelon The new version is not out yet. We automatically deploy once a day.

**Comment by AeroEchelon** [comment]
Ah okay; will check again once it is out.

**Comment by AeroEchelon** [comment]
Confirmed as of version  17.7.20.1325 that this issue is resolved. ✌️
